interface Order {
  id: string;
  customerName: string;
  item: string;
  quantity: number;
  status: string;
  date: string;
  time: string;
}

export const orders: Order[] = [
  {
    id: crypto.randomUUID(),
    customerName: "John Doe",
    item: "Apple",
    quantity: 10,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Doe",
    item: "Banana",
    quantity: 5,
    status: "completed",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "John Smith",
    item: "Orange",
    quantity: 15,
    status: "cancelled",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Smith",
    item: "Grapes",
    quantity: 20,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "John Doe",
    item: "Apple",
    quantity: 10,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Doe",
    item: "Banana",
    quantity: 5,
    status: "completed",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "John Smith",
    item: "Orange",
    quantity: 15,
    status: "cancelled",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Smith",
    item: "Grapes",
    quantity: 20,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "John Doe",
    item: "Apple",
    quantity: 10,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Doe",
    item: "Banana",
    quantity: 5,
    status: "completed",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "John Smith",
    item: "Orange",
    quantity: 15,
    status: "cancelled",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Smith",
    item: "Grapes",
    quantity: 20,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "John Doe",
    item: "Apple",
    quantity: 10,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Doe",
    item: "Banana",
    quantity: 5,
    status: "completed",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "John Smith",
    item: "Orange",
    quantity: 15,
    status: "cancelled",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Smith",
    item: "Grapes",
    quantity: 20,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "John Doe",
    item: "Apple",
    quantity: 10,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Doe",
    item: "Banana",
    quantity: 5,
    status: "completed",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "John Smith",
    item: "Orange",
    quantity: 15,
    status: "cancelled",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Smith",
    item: "Grapes",
    quantity: 20,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "John Doe",
    item: "Apple",
    quantity: 10,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Doe",
    item: "Banana",
    quantity: 5,
    status: "completed",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "John Smith",
    item: "Orange",
    quantity: 15,
    status: "cancelled",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Smith",
    item: "Grapes",
    quantity: 20,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "John Doe",
    item: "Apple",
    quantity: 10,
    status: "pending",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
  {
    id: crypto.randomUUID(),
    customerName: "Jane Doe",
    item: "Banana",
    quantity: 5,
    status: "completed",
    date: new Date().toLocaleDateString(),
    time: new Date().toLocaleTimeString(),
  },
];
